%% Mechanistic model-driven exometabolomic characterization of human dopaminergic neuronal metabolism
% Pipeline to generate results of the article "Mechanistic model-driven exometabolomic 
% characterization of human dopaminergic neuronal metabolism".
% 
% Note: The results are saved in the directory specified by each driver, currently 
% the main results are saved in:

% ~/work/sbgCloud/programReconstruction/projects/exoMetDN/results/codeResults/iDN1
%% XomicsToModel data preparation
% Recon3D
% Preparation of the generic Recon3D model with thermodynamic data, and the 
% addition of names for reactions where it is missing. It excludes the  expression  
% of the reactions because that isspecific information which it  is included in 
% XomicsToModel. The generic model is saved in :

% '~/work/sbgCloud/programExperimental/projects/xomics/data/Recon3D_301/Recon3DModel_301_xomics_input.mat'
driver_prepareRecon3Model
% Specific data preprocessing
% The tables transcriptomicsData and exoMet, which are used in the variable  
% |specificData|, are generated using the function |transcriptomics2genes|. The 
% external files are saved in:

% ~/work/sbgCloud/programReconstruction/projects/exoMetDN/data/xomics
driver_specificDataPreprocessing
%% iDopaNeuro models generation
% |XomicsToMultipleModels| Generate iDopaNeuro model conditions with different 
% conditions using the function  |XomicsToMultipleModels|. The conditions used 
% are:
% 
% Generic model: Recon3DModel_301_xomics_input
%% 
% # cobraSolver: gurobi
% # tissueSpecificSolver: fastCore - thermoKernel
% # activeGenesApproach: deleteModelGenes - oneRxnPerActiveGene
% # transcriptomicThreshold: [0 2]
% # limitBounds: [1e3 1e4 1e5]
% # inactiveGenesTranscriptomics: [true false]
% # closeIons: [true false]
% # curationOverOmics: [true false]
%% 
% The models are saved in:

% ~/work/sbgCloud/programReconstruction/projects/exoMetDN/results/codeResults/iDN1
driver_createMultipleIDNModels
%% Predictive capacity
% The predictive capacity of each model generated by |driver_createMultipleIDNModels| 
% is evaluated using the |modelPredictiveCapacity| function to ifentify the model  
% with the predictive capacity. Save the results as accuracy.mat on each directory 
% The models are saved in:

% ~/work/sbgCloud/programReconstruction/projects/exoMetDN/results/codeResults/iDN1
driver_testiDNmodelPredictiveCapacity
%% iDopaNeuro models
% Identify the most accurate model based on the results of driver_testiDNmodelPredictiveCapacity.m. 
% The information gathered from each model is used to identify two sets of conditions:
%% 
% * The objective giving the highest predictive capacity, irrespective of the 
% model generation parameters
% * The model
%% 
% The most accurate models are saved in:

% ~/work/sbgCloud/programReconstruction/projects/exoMetDN/results/codeResults/iDN1
driver_identifyMostAccurateiDNModel
% Models comparison
% Generates a venn diagram that compares the core reactions between the iDopaNeuroCT  
% and iDopaNeuroC models. Additionally, it creates a general comparison of both 
% models (for example dimentions, essential pathways, main energy sources). Furthermore 
% it compares the models predictions to the exoMetabolomic data and creates predictions 
% for metabolites not yet measured. Last, it compares atp and nadh utilisation 
% network in both models. The results are saved in:

% ~/work/sbgCloud/programReconstruction/projects/exoMetDN/results/codeResults/iDN1
driver_iDopaNeuroModelsComparison
%% 
% Generates a comparison of predictions by iDopaNeuroCT and iDopaNeuroC models

driver_iDopaNeuroCvsCT
%% Statistics
% Generates predictions in response to various perturbations

driver_iDopaNeuroPerturbation
%% Statistics
% Generates a venn diagram that describes the sources of exchange metabolites 
% in the iDopaNeuro models.

driver_vennMetabolites

% Bibliomics genes and reactions
% Shows the bibliomics active genes and reactions in the iDopaNeuro models

driver_activeInactiveGenesRxns
%% Sparse FBA
% Comparison of the fraction of reactions in (red) and out (blue) of the minimal 
% flux vector in each metabolic subsystem of the iDopaNeuro modesl, obtained by 
% minimising the function Ψ(v):=||v||_{0} subject to v∈Ω, to predict the minimum 
% number of reactions that are required to be active to satisfy dopaminergic neuron 
% specific constraints on the steady-state flux space Ω. 

driver_sparseFBA
%% Comparison of iDopaNeuro CT vs C predictions

driver_iDopaNeuroCvsCT
%% Metabolic perturbations and validation

modelName='iDopaNeuroC';
driver_iDopaNeuroPerturbation
%% Metabolic perturbations and validation - iDopaNeuroCT

modelName='iDopaNeuroCT';
driver_iDopaNeuroPerturbation
%% Uncertainty reduction
% Uniform sampling of feasible solution space, was used to predict a set of 
% metabolites that could potentially be secreted by the iDopaNeuro models. In 
% principle, all of these metabolites should be considered for targeted metabolomic 
% analyses in exometabolomic experiments.

driver_uncertaintyReduction